# Generated by Django 4.2.16 on 2024-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingAddress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingCity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingCountry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billingPostcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingPostcode',
        ),
    ]
